services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "root@123"
      ACCEPT_EULA: "Y"
      DATABASE: "root"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
volumes:
  sqlserver_data:
    driver: local